# this file exists because Docker Hub can't make images out of build stages
# so this is a bit redundnat with Dockerfile in this repo
# but it lets us host two images, mostly the same, on Hub
FROM bretfisher/jekyll:latest

COPY docker-entrypoint.sh /usr/local/bin/

# on every container start, check if Gemfile exists and warn if it's missing
ENTRYPOINT [ "docker-entrypoint.sh" ]

CMD [ "bundle", "exec", "jekyll", "serve", "--force_polling", "-H", "0.0.0.0", "-P", "4000" ]
