---
name: Build and Push Images

on:
  # we want pull requests so we can build(test) but not push to image registry
  pull_request:
    branches:
      - 'main'
    # only build when important files change
    paths:
      - 'Dockerfile'
      - '.github/workflows/call-docker-build.yaml'
      - 'docker-entrypoint.sh'
  push:
    branches:
      - 'main'
    # only build when important files change
    paths:
      - 'Dockerfile'
      - '.github/workflows/call-docker-build.yaml'
      - 'docker-entrypoint.sh'
  schedule:
    # re-run montly to keep image fresh with upstream base images
    - cron: '0 12 15 * *'


jobs:
  build-jekyll-image:
    # use Reusable Workflows
    # https://docs.github.com/en/actions/learn-github-actions/reusing-workflows
     name: Call Docker Build Jekyll

    uses: bretfisher/docker-build-workflow/.github/workflows/reusable-docker-build.yaml@main

    permissions:
      contents: read
      packages: write # needed to push docker image to ghcr.io
      pull-requests: write # needed to create and update comments in PRs
    
    secrets:

      # Only needed if with:dockerhub-enable is true below
      dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}

      # Only needed if with:dockerhub-enable is true below
      # https://hub.docker.com/settings/security
      dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}

    with:
      dockerhub-enable: true
      ghcr-enable: true
      image-names: |
        bretfisher/jekyll
        ghcr.io/bretfisher/jekyll
      platforms: linux/amd64,linux/arm64,linux/arm/v7

  build-jekyll-serve-image:
    # use Reusable Workflows
    # https://docs.github.com/en/actions/learn-github-actions/reusing-workflows
    name: Call Docker Build Jekyll-Serve

    uses: bretfisher/docker-build-workflow/.github/workflows/reusable-docker-build.yaml@main

    needs: build-jekyll-image

    permissions:
      contents: read
      packages: write # needed to push docker image to ghcr.io
      pull-requests: write # needed to create and update comments in PRs
    
    secrets:

      # Only needed if with:dockerhub-enable is true below
      dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}

      # Only needed if with:dockerhub-enable is true below
      # https://hub.docker.com/settings/security
      dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}

    with:
      dockerhub-enable: true
      ghcr-enable: true
      image-names: |
        bretfisher/jekyll-serve 
        ghcr.io/bretfisher/jekyll-serve
      platforms: linux/amd64,linux/arm64,linux/arm/v7
      file: Dockerfile.serve

