---
name: Docker Build

on:
  push:
    branches:
      - "main"
    paths:
      - "Dockerfile"
      - ".github/workflows/call-docker-build.yaml"
      - "docker-entrypoint.sh"
  pull_request:
    paths:
      - "Dockerfile"
      - ".github/workflows/call-docker-build.yaml"
      - "docker-entrypoint.sh"

# cancel any previously-started, yet still active runs of this workflow on the same branch
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

# reset permissions to none at the workflow level
# we'll set them at the job level below
permissions: {}

jobs:
  build-jekyll-image:
    # use Reusable Workflows
    # https://docs.github.com/en/actions/learn-github-actions/reusing-workflows
    name: Call Docker Build Jekyll

    # NOTE: zizmor scanner rule ignore added because we control sha pins via reusable workflow, not calling workflow
    uses: bretfisher/docker-build-workflow/.github/workflows/reusable-docker-build.yaml@main # zizmor: ignore[unpinned-uses]

    # set permissions here to be equal or greater than what's required in the Reusable Workflow
    # Permissions set here for the GITHUB_TOKEN are then passed to the Reusable Workflow
    # Calling permissions must be equal to or greater than these reusable permissions for it to work
    # https://docs.github.com/en/actions/using-workflows/reusing-workflows#supported-keywords-for-jobs-that-call-a-reusable-workflow
    permissions:
      contents: read
      packages: write # needed to push docker image to ghcr.io
      pull-requests: write # needed to create and update comments in PRs

    secrets:
      dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}

    with:
      dockerhub-enable: true
      ghcr-enable: true
      image-names: |
        bretfisher/jekyll
        ghcr.io/bretfisher/jekyll
      platforms: linux/amd64,linux/arm64
      target: jekyll

  build-jekyll-serve-image:
    # use Reusable Workflows
    # https://docs.github.com/en/actions/learn-github-actions/reusing-workflows
    name: Call Docker Build Jekyll-Serve

    # NOTE: zizmor scanner rule ignore added because we control sha pins via reusable workflow, not calling workflow
    uses: bretfisher/docker-build-workflow/.github/workflows/reusable-docker-build.yaml@main # zizmor: ignore[unpinned-uses]

    needs: build-jekyll-image

    # if: github.event_name == 'push'

    permissions:
      contents: read
      packages: write # needed to push docker image to ghcr.io
      pull-requests: write # needed to create and update comments in PRs

    secrets:
      dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}

    with:
      dockerhub-enable: true
      ghcr-enable: true
      image-names: |
        bretfisher/jekyll-serve 
        ghcr.io/bretfisher/jekyll-serve
      platforms: linux/amd64,linux/arm64
      target: jekyll-serve
