---
name: Build and Push Images

on:
  # we want pull requests so we can build(test) but not push to image registry
  pull_request:
    branches:
      - 'main'
    # only build when important files change
    paths:
      - 'Dockerfile'
      - '.github/workflows/docker-build-and-push.yml'
      - 'docker-entrypoint.sh'
  push:
    branches:
      - 'main'
    # only build when important files change
    paths:
      - 'Dockerfile'
      - '.github/workflows/docker-build-and-push.yml'
      - 'docker-entrypoint.sh'
  schedule:
    # re-run montly to keep image fesh with upstream base images
    - cron: '0 12 15 * *'
  workflow_dispatch:
    # run whenever we want!

jobs:
  build-jekyll-image:
    # use Reusable Workflows
    # https://docs.github.com/en/actions/learn-github-actions/reusing-workflows
    uses: bretfisher/github-actions-templates/.github/workflows/docker-build-and-push.yaml@main
    with:
      image-names: |
          bretfisher/jekyll
          ghcr.io/bretfisher/jekyll
    secrets:
      dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}

  build-jekyll-serve-image:
    # use Reusable Workflows
    # https://docs.github.com/en/actions/learn-github-actions/reusing-workflows
    uses: bretfisher/github-actions-templates/.github/workflows/docker-build-and-push.yaml@main
    needs: build-jekyll-image
    with:
      image-names: |
          bretfisher/jekyll-serve 
          ghcr.io/bretfisher/jekyll-serve
    secrets:
      dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
